# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NEGroupCall-iOS' do
  use_frameworks!

pod 'NERtcSDK', '4.2.112'
pod 'Nama-lite', '7.1.2'
pod 'NIMSDK_LITE', '7.8.4'
pod 'Masonry'
pod 'SDWebImage', '~> 5.7.1'
pod 'Toast'
pod 'MJRefresh'
pod 'YYModel'
pod 'M80AttributedLabel', '~> 1.3.1'
pod 'NELivePlayer', '~> 2.7.1'
pod 'IQKeyboardManager', '~> 6.5.6'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'Reachability'
pod 'YXAlog_iOS', '~> 0.1.0'

end
