# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NLiteAVDemo' do
  use_frameworks!

pod 'NERtcSDK', '~> 3.7.3'
#pod 'NIMSDK_LITE', '~> 8.1.0'
pod 'Masonry'
pod 'SDWebImage', '~> 5.7.1'
pod 'Toast'
pod 'MJRefresh'
pod 'YYModel'
pod 'Nama-lite', '7.1.2'
pod 'IQKeyboardManager', '~> 6.5.6'
end
